// Tencent is pleased to support the open source community by making tRPC available.
// Copyright (C) 2023 THL A29 Limited, a Tencent company. All rights reserved.
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.

// Copyright 2015 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file may have been modified by THL A29 Limited ("Tencent Modifications").
// All Tencent Modifications are Copyright (C) 2023 THL A29 Limited.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: trpc/api/annotations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_trpc_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         50201,
		Name:          "trpc.api.http",
		Tag:           "bytes,50201,opt,name=http",
		Filename:      "trpc/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Schema)(nil),
		Field:         50201,
		Name:          "trpc.api.openapiv2_schema",
		Tag:           "bytes,50201,opt,name=openapiv2_schema",
		Filename:      "trpc/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional trpc.api.HttpRule http = 50201;
	E_Http = &file_trpc_api_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional trpc.api.Schema openapiv2_schema = 50201;
	E_Openapiv2Schema = &file_trpc_api_annotations_proto_extTypes[1]
)

var File_trpc_api_annotations_proto protoreflect.FileDescriptor

const file_trpc_api_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1atrpc/api/annotations.proto\x12\btrpc.api\x1a\x13trpc/api/http.proto\x1a\x18trpc/api/openapiv2.proto\x1a google/protobuf/descriptor.proto:H\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\x99\x88\x03 \x01(\v2\x12.trpc.api.HttpRuleR\x04http:^\n" +
	"\x10openapiv2_schema\x12\x1f.google.protobuf.MessageOptions\x18\x99\x88\x03 \x01(\v2\x10.trpc.api.SchemaR\x0fopenapiv2SchemaBM\n" +
	"\x1dcom.tencent.trpc.protobuf.extZ,trpc.group/trpc/trpc-protocol/pb/go/trpc/apib\x06proto3"

var file_trpc_api_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil),  // 0: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
	(*HttpRule)(nil),                    // 2: trpc.api.HttpRule
	(*Schema)(nil),                      // 3: trpc.api.Schema
}
var file_trpc_api_annotations_proto_depIdxs = []int32{
	0, // 0: trpc.api.http:extendee -> google.protobuf.MethodOptions
	1, // 1: trpc.api.openapiv2_schema:extendee -> google.protobuf.MessageOptions
	2, // 2: trpc.api.http:type_name -> trpc.api.HttpRule
	3, // 3: trpc.api.openapiv2_schema:type_name -> trpc.api.Schema
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trpc_api_annotations_proto_init() }
func file_trpc_api_annotations_proto_init() {
	if File_trpc_api_annotations_proto != nil {
		return
	}
	file_trpc_api_http_proto_init()
	file_trpc_api_openapiv2_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trpc_api_annotations_proto_rawDesc), len(file_trpc_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_trpc_api_annotations_proto_goTypes,
		DependencyIndexes: file_trpc_api_annotations_proto_depIdxs,
		ExtensionInfos:    file_trpc_api_annotations_proto_extTypes,
	}.Build()
	File_trpc_api_annotations_proto = out.File
	file_trpc_api_annotations_proto_goTypes = nil
	file_trpc_api_annotations_proto_depIdxs = nil
}
