// Tencent is pleased to support the open source community by making tRPC available.
// Copyright (C) 2023 THL A29 Limited, a Tencent company. All rights reserved.
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: trpc/api/openapiv2.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message option schema
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonSchema    *JSONSchema            `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_trpc_api_openapiv2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_trpc_api_openapiv2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_trpc_api_openapiv2_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetJsonSchema() *JSONSchema {
	if x != nil {
		return x.JsonSchema
	}
	return nil
}

// `JSONSchema` represents properties from JSON SCHEMA taken,and as used, in
//
//	the OpenAPI v2 spec.
type JSONSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      []string               `protobuf:"bytes,1,rep,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONSchema) Reset() {
	*x = JSONSchema{}
	mi := &file_trpc_api_openapiv2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONSchema) ProtoMessage() {}

func (x *JSONSchema) ProtoReflect() protoreflect.Message {
	mi := &file_trpc_api_openapiv2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONSchema.ProtoReflect.Descriptor instead.
func (*JSONSchema) Descriptor() ([]byte, []int) {
	return file_trpc_api_openapiv2_proto_rawDescGZIP(), []int{1}
}

func (x *JSONSchema) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

var File_trpc_api_openapiv2_proto protoreflect.FileDescriptor

const file_trpc_api_openapiv2_proto_rawDesc = "" +
	"\n" +
	"\x18trpc/api/openapiv2.proto\x12\btrpc.api\"?\n" +
	"\x06Schema\x125\n" +
	"\vjson_schema\x18\x01 \x01(\v2\x14.trpc.api.JSONSchemaR\n" +
	"jsonSchema\"(\n" +
	"\n" +
	"JSONSchema\x12\x1a\n" +
	"\brequired\x18\x01 \x03(\tR\brequiredBM\n" +
	"\x1dcom.tencent.trpc.protobuf.extZ,trpc.group/trpc/trpc-protocol/pb/go/trpc/apib\x06proto3"

var (
	file_trpc_api_openapiv2_proto_rawDescOnce sync.Once
	file_trpc_api_openapiv2_proto_rawDescData []byte
)

func file_trpc_api_openapiv2_proto_rawDescGZIP() []byte {
	file_trpc_api_openapiv2_proto_rawDescOnce.Do(func() {
		file_trpc_api_openapiv2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trpc_api_openapiv2_proto_rawDesc), len(file_trpc_api_openapiv2_proto_rawDesc)))
	})
	return file_trpc_api_openapiv2_proto_rawDescData
}

var file_trpc_api_openapiv2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trpc_api_openapiv2_proto_goTypes = []any{
	(*Schema)(nil),     // 0: trpc.api.Schema
	(*JSONSchema)(nil), // 1: trpc.api.JSONSchema
}
var file_trpc_api_openapiv2_proto_depIdxs = []int32{
	1, // 0: trpc.api.Schema.json_schema:type_name -> trpc.api.JSONSchema
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trpc_api_openapiv2_proto_init() }
func file_trpc_api_openapiv2_proto_init() {
	if File_trpc_api_openapiv2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trpc_api_openapiv2_proto_rawDesc), len(file_trpc_api_openapiv2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trpc_api_openapiv2_proto_goTypes,
		DependencyIndexes: file_trpc_api_openapiv2_proto_depIdxs,
		MessageInfos:      file_trpc_api_openapiv2_proto_msgTypes,
	}.Build()
	File_trpc_api_openapiv2_proto = out.File
	file_trpc_api_openapiv2_proto_goTypes = nil
	file_trpc_api_openapiv2_proto_depIdxs = nil
}
