// Code generated by trpc-go/trpc-go-cmdline v2.4.0. DO NOT EDIT.
// source: reflection.proto

package reflection

import (
	"context"
	"errors"
	"fmt"

	_ "git.code.oa.com/trpc-go/trpc-go"
	"git.code.oa.com/trpc-go/trpc-go/client"
	"git.code.oa.com/trpc-go/trpc-go/codec"
	_ "git.code.oa.com/trpc-go/trpc-go/http"
	"git.code.oa.com/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ServerReflectionService defines service.
type ServerReflectionService interface {
	ServiceReflectionInfo(ctx context.Context, req *ServerReflectionRequest) (*ServerReflectionResponse, error)
}

func ServerReflectionService_ServiceReflectionInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ServerReflectionRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ServerReflectionService).ServiceReflectionInfo(ctx, reqbody.(*ServerReflectionRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ServerReflectionServer_ServiceDesc descriptor for server.RegisterService.
var ServerReflectionServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.reflection.v1.ServerReflection",
	HandlerType: ((*ServerReflectionService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.reflection.v1.ServerReflection/ServiceReflectionInfo",
			Func: ServerReflectionService_ServiceReflectionInfo_Handler,
		},
	},
}

// RegisterServerReflectionService registers service.
func RegisterServerReflectionService(s server.Service, svr ServerReflectionService) {
	if err := s.Register(&ServerReflectionServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ServerReflection register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedServerReflection struct{}

func (s *UnimplementedServerReflection) ServiceReflectionInfo(ctx context.Context, req *ServerReflectionRequest) (*ServerReflectionResponse, error) {
	return nil, errors.New("rpc ServiceReflectionInfo of service ServerReflection is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ServerReflectionClientProxy defines service client proxy
type ServerReflectionClientProxy interface {
	ServiceReflectionInfo(ctx context.Context, req *ServerReflectionRequest, opts ...client.Option) (rsp *ServerReflectionResponse, err error)
}

type ServerReflectionClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewServerReflectionClientProxy = func(opts ...client.Option) ServerReflectionClientProxy {
	return &ServerReflectionClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ServerReflectionClientProxyImpl) ServiceReflectionInfo(ctx context.Context, req *ServerReflectionRequest, opts ...client.Option) (*ServerReflectionResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.reflection.v1.ServerReflection/ServiceReflectionInfo")
	msg.WithCalleeServiceName(ServerReflectionServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("reflection")
	msg.WithCalleeServer("v1")
	msg.WithCalleeService("ServerReflection")
	msg.WithCalleeMethod("ServiceReflectionInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ServerReflectionResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
