package(default_visibility = ["//visibility:public"])

proto_library(
    name = "trpc_options_proto",
    srcs = [
        "trpc_options.proto",
    ],
    deps = [
        "@com_google_protobuf//:descriptor_proto",
    ],
)
