package(default_visibility = ["//visibility:public"])

proto_library(
    name = "swagger_proto",
    srcs = [
        "swagger.proto",
    ],
    deps = [
        "@com_google_protobuf//:descriptor_proto",
    ],
)
