cc_proto_library(
    name = "cc_trpc_proto",
    deps = [
        "//trpc:trpc_proto",
    ],
)

cc_proto_library(
    name = "cc_trpc_options_proto",
    deps = [
        "//trpc/proto:trpc_options_proto",
    ],
)

cc_proto_library(
    name = "cc_annotations_proto",
    deps = [
        "//trpc/api:annotations_proto",
    ],
)

cc_proto_library(
    name = "cc_http_proto",
    deps = [
        "//trpc/api:http_proto",
    ],
)

cc_proto_library(
    name = "cc_swagger_proto",
    deps = [
        "//trpc/swagger:swagger_proto",
    ],
)

cc_proto_library(
    name = "cc_validate_proto",
    deps = [
        "//trpc/validate:validate_proto",
    ],
)
