cc_proto_library(
    name = "cc_trpc_proto",
    deps = [
        "//trpc/proto:trpc_proto",
    ],
)

cc_proto_library(
    name = "cc_trpc_options_proto",
    deps = [
        "//trpc/proto:trpc_options_proto",
    ],
)
