package(default_visibility = ["//visibility:public"])

proto_library(
    name = "validate_proto",
    srcs = [
        "validate.proto",
    ],
    deps = [
        "@com_google_protobuf//:descriptor_proto",
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)
