// Tencent is pleased to support the open source community by making tRPC available.
// Copyright (C) 2023 THL A29 Limited, a Tencent company. All rights reserved.
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: trpc/v2/api/annotations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_trpc_v2_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         1157,
		Name:          "trpc.v2.api.http",
		Tag:           "bytes,1157,opt,name=http",
		Filename:      "trpc/v2/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional trpc.v2.api.HttpRule http = 1157;
	E_Http = &file_trpc_v2_api_annotations_proto_extTypes[0]
)

var File_trpc_v2_api_annotations_proto protoreflect.FileDescriptor

const file_trpc_v2_api_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1dtrpc/v2/api/annotations.proto\x12\vtrpc.v2.api\x1a\x16trpc/v2/api/http.proto\x1a google/protobuf/descriptor.proto:J\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\x85\t \x01(\v2\x15.trpc.v2.api.HttpRuleR\x04httpBP\n" +
	"\x1dcom.tencent.trpc.protobuf.extZ/trpc.group/trpc/trpc-protocol/pb/go/trpc/v2/apib\x06proto3"

var file_trpc_v2_api_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
	(*HttpRule)(nil),                   // 1: trpc.v2.api.HttpRule
}
var file_trpc_v2_api_annotations_proto_depIdxs = []int32{
	0, // 0: trpc.v2.api.http:extendee -> google.protobuf.MethodOptions
	1, // 1: trpc.v2.api.http:type_name -> trpc.v2.api.HttpRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trpc_v2_api_annotations_proto_init() }
func file_trpc_v2_api_annotations_proto_init() {
	if File_trpc_v2_api_annotations_proto != nil {
		return
	}
	file_trpc_v2_api_http_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trpc_v2_api_annotations_proto_rawDesc), len(file_trpc_v2_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_trpc_v2_api_annotations_proto_goTypes,
		DependencyIndexes: file_trpc_v2_api_annotations_proto_depIdxs,
		ExtensionInfos:    file_trpc_v2_api_annotations_proto_extTypes,
	}.Build()
	File_trpc_v2_api_annotations_proto = out.File
	file_trpc_v2_api_annotations_proto_goTypes = nil
	file_trpc_v2_api_annotations_proto_depIdxs = nil
}
